### ISSUE TITLE
Project not starting

### ISSUE THREAD

**Issue by akashtalole** [flowforge/docker-compose#45]
### Current Behavior

getting below error for project nodered
`Launcher Started
Loading project settings
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError: getaddrinfo EAI_AGAIN iotsim
    at ClientRequest.<anonymous> (/usr/src/flowforge-nr-launcher/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/usr/src/flowforge-nr-launcher/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1666168500880,
    socket: 1666168500880,
    lookup: 1666168505886,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1666168505886,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 5006,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5006
    }
  }
}
`

### Expected Behavior

project nodered instance should run

### Steps To Reproduce

create project

### Environment

- FlowForge version: 0.10
- Node.js version: <docker-compose>
- npm version: <docker-compose>
- Platform/OS: Ubuntu 22.04
- Browser: Chrome

**Comment by akashtalole** [comment]
i made mistake in api_url. it is working with api_url: http://forge:3000. Thanks @hardillb

**Comment by hardillb** [comment]
Thanks for raising this as it does show we need to catch those errors
